version: 2
workflows:
  android-build:
    name: Android Native Build Workflow # Memastikan Gradle digunakan untuk build
    scripts:
      - echo "Setting up Android environment"
      - chmod +x ./gradlew
      - echo "Installing Java 11"
      - sudo apt-get update  # Memperbarui daftar package
      - sudo apt-get install -y openjdk-11-jdk  # Install Java 11
      - java -version 
      - ./gradlew clean  # Membersihkan build sebelumnya
      - ./gradlew assembleRelease  # Membangun APK release
      - echo "Build APK selesai"
      - ./gradlew assembleDebug  # Membangun APK debug (opsional)
      - echo "Build APK Debug selesai"
    artifacts:
      - app/build/outputs/apk/release/app-release.apk  # Output APK release
      - app/build/outputs/apk/debug/app-debug.apk  # Output APK debug (opsional)
